- name: Manjaro Linux Upgrade
  hosts: rpi_hosts
  gather_facts: false


  tasks:
    - name: Upgrade packages
      become: true
      shell:
          "pacman-mirrors -f; pacman -Syyuu"

    - name: Remove obsolete packages
      become: true
      shell:
          "pacman -Rcns $(pacman -Qdtq) || true"
