- name: Manjaro Linux Upgrade
  hosts: rpi_hosts
  gather_facts: false
  become: true


  tasks:
    - name: Upgrade packages
      shell:
          "pacman-mirrors -f; pacman -Syyuu --noconfirm"

    - name: Remove obsolete packages
      shell:
          "pacman -Rcns $(pacman -Qdtq) --noconfirm || true"
